// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitUserImage(arg1, arg2) {
  return window['go']['main']['App']['CommitUserImage'](arg1, arg2);
}

export function GetUserImgPath() {
  return window['go']['main']['App']['GetUserImgPath']();
}
